name: Daily TVMaze ETL
on:
  schedule:
    - cron: '@once' # Runs once
  workflow_dispatch:    # Allows manual testing

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - run: pip install -r requirements.txt
      - run: python src/pipeline.py
      - name: Commit Data
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add data/
          git commit -m "ðŸ¤– Automated Data Update" || exit 0
          git push
